### ISSUE TITLE
Logo issues

### ISSUE THREAD

**Issue by bharathikannan573** [hepzi05/tamilil-new#4]

**Comment by bharathikannan573** [comment]
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/dashboard.php
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/domain_thankyou.php
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/domain_check.php
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/content_request.php

**Comment by hepzi05** [comment]
No issue - http://localhost/temp/tamilil_git/tamilil-new-dev/pages/dashboard.php
Found issue on - http://localhost/new-tamilil/tamilil-new

**Comment by bharathikannan573** [comment]
completed
