### ISSUE TITLE
Incorrect path in logo

### ISSUE THREAD

**Issue by hepzi05** [hepzi05/tamilil-new#5]

**Comment by hepzi05** [comment]
Fix index page logo issue

**Comment by bharathikannan573** [comment]
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/domain_check.php
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/domain_thankyou.php
http://localhost/temp/tamilil_git/tamilil-new-dev/pages/content_request.php

**Comment by bharathikannan573** [comment]
completed
